### ISSUE TITLE
Enemy Warp particle animation is not done

### ISSUE THREAD

**Issue by Antaran** [SunriseHirame/Arcade#6]
stupid sexy flanders!

**Comment by Antaran** [comment]
Warp-effect added to textures, leaving this open until verified to be working.

**Comment by SunriseHirame** [comment]
Tuosta puuttuu kokonaan animaatio tai muu vastaava data, ei ole kuin animaatio meshi

**Comment by Antaran** [comment]
eh...that's why you shouldn't do work when tired...It seems I left the "animation" box unticked from 3ds max export options. Also applied material to particles.

**Comment by Antaran** [comment]
Ok there's an issue with importing particle systems from 3ds max to unity. I'm working on a solution.

**Comment by Antaran** [comment]
Going to assume that the Warp animation I submitted is a good enough placeholder.
